name: Release

on:
  push:
    tags:
      - 'v*'
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags

      - name: Verify tag is on main branch
        run: |
          # Get the commit SHA for the tag
          TAG_COMMIT=$(git rev-parse ${{ github.ref }})

          # Check if the commit is on the main branch
          if ! git branch -r --contains $TAG_COMMIT | grep -q 'origin/main'; then
            echo "Error: Tag ${{ github.ref_name }} is not on the main branch"
            exit 1
          fi

          echo "✓ Tag ${{ github.ref_name }} is on main branch"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build
        run: npm run build

      - name: Publish to npm
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Extract version from tag
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        run: |
          gh release create "${{ github.ref_name }}" \
            --title "Release v${{ steps.version.outputs.VERSION }}" \
            --notes "See [CHANGELOG.md](https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md) for details." \
            --verify-tag
        env:
          GH_TOKEN: ${{ github.token }}
